os: linux
#dist: xenial
dist: bionic
language: c

matrix:
  include:
    - arch: amd64
    - arch: arm64
    - arch: ppc64le
    #- name: "s390x default condition"
    - arch: s390x
    #- name: "s390x disabling IPv6"
    #  arch: s390x
     # before_script:
    #    - ip a
      #  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
     #   - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
     #   - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
     #   - ip a

install: true
before_install:
  - apt list -a software-properties-common
  # - sudo apt-get install strace
install: true
script:
  - ip a
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  # - sudo -E strace -f apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
